### ISSUE TITLE
ASN type is not available

### ISSUE THREAD

**Issue by andykno** [ipdata/java#2]
The ASN type is not available in the data model.

Instead of a `type` attribute, there is an `isp` attribute in the `AsnModel` class:
https://github.com/ipdata/java/blob/master/src/main/java/io/ipdata/client/model/AsnModel.java#L13

The `isp` attribute seems to be always null.

**Comment by yassine** [comment]
Thanks for reporting the issue.
A fix will be released at latest by next week.

**Comment by yassine** [comment]
Please checkout the 'type' field on the ASN model in the 0.1.1 release.
Release is available via Maven Central as documented in README file.

**Comment by andykno** [comment]
Works fine. Thanks!
